# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main

pool:
  vmImage: ubuntu-latest

variables:
- name: bkresourcegroup
  value: 'rg-latam-modernization-peru-westus-001'
- name: bkstorage
  value: 'terraformperubackend'
- name: bkcontainer
  value: 'tfstate'
- name: bkstrgkey
  value: 'pipeline.terraform.tfstate'

stages:
  - stage: tfinit
    jobs:
      - job: init
        continueOnError: false
        steps:
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Coeperuterraformservicetestconnection'
              backendAzureRmResourceGroupName: 'rg-latam-modernization-peru-westus-001'
              backendAzureRmStorageAccountName: 'terraformperubackend'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'pipeline.terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    condition: succeeded('tfinit')
    dependsOn: tfinit
    jobs:
      - job: apply
        steps:
          - task: TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Coeperuterraformservicetestconnection'
              backendAzureRmResourceGroupName: 'rg-latam-modernization-peru-westus-001'
              backendAzureRmStorageAccountName: 'terraformperubackend'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'pipeline.terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Coeperuterraformservicetestconnection'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Coeperuterraformservicetestconnection'
        



