# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- main

pool:
  vmImage: ubuntu-latest

variables:
- name: bkresourcegroup
  value: 'rg-latam-modernization-peru-westus-001'
- name: bkstorage
  value: 'terraformperubackend'
- name: bkcontainer
  value: 'tfstate'
- name: bkstrgkey
  value: 'pipeline.terraform.tfstate'

#steps:
#- task: InstallSSHKey@0
#  inputs:
#    knownHostsEntry: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
#    sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCRfYWbhVQbC0k0Nl0aDY7y5gQQXCF9sLHfDFOuWijkeLTuBWLWlc1Te0mVq2+zQfdD6B6YS8b2Lnn7U4lCAupv2BxNvmaLEPjjgDTeNPhi+rlRC7Sm506zAoIDnrEuRnJJzpSAZEdDcPxU6VRJcSQDfty5IAEbQTZiWrjlJaRGBb+tY3kUIMtOnlDCermK1JOdwcxNp/j9WCO6q2+EuiVX/wlvDCg8SXDzac53sMoLEvsXtISe6epVtupcpMfs9H8Dy81UMSWxGZzNHpakY6eqe+JY2FCCkycF9UXmVgNvUKICCQSSRJYdrZOEfHmQbc5odmscJXgPtZ4ka+YRmmkpmAk/0vuuAXuRyPmnxLzTxoMwxn+l+S0/aUeGwnAW2B7tDe0c5PlZDcJ7yvtng47l+6Asy68kyFVD1GxmRmY5gr8g7bJNKh5Bi1r9Cgp86MAh4iLC9RYYCcRFymQ3ZBaAIsbtz4u0cja5aTrNhLSc4qwf3ncdmfSSNSStjiXBjSH6brGHgpdzjCX5JB2iG2nbDkp1zltdA6yjIv8HnfY/h9GFcYcZ5tqMJSGD/zCyAI8TMHehqTn4LnkpX4N24VqEde1sFcKagQgS2d/hYzHntkQik1A7jOF4DHvqvDH7FdC5IhkOtG36geO+8jVDQYzs0ig7GJIJuHj2xV2bncE/OQ== rodolfomincholachavez@ingenieros.com"
#    sshKeySecureFile: 'id_rsa'
#  displayName: installgithubssh

stages:
  - stage: tfinit
    jobs:
      - job: init
        continueOnError: false
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
              sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCRfYWbhVQbC0k0Nl0aDY7y5gQQXCF9sLHfDFOuWijkeLTuBWLWlc1Te0mVq2+zQfdD6B6YS8b2Lnn7U4lCAupv2BxNvmaLEPjjgDTeNPhi+rlRC7Sm506zAoIDnrEuRnJJzpSAZEdDcPxU6VRJcSQDfty5IAEbQTZiWrjlJaRGBb+tY3kUIMtOnlDCermK1JOdwcxNp/j9WCO6q2+EuiVX/wlvDCg8SXDzac53sMoLEvsXtISe6epVtupcpMfs9H8Dy81UMSWxGZzNHpakY6eqe+JY2FCCkycF9UXmVgNvUKICCQSSRJYdrZOEfHmQbc5odmscJXgPtZ4ka+YRmmkpmAk/0vuuAXuRyPmnxLzTxoMwxn+l+S0/aUeGwnAW2B7tDe0c5PlZDcJ7yvtng47l+6Asy68kyFVD1GxmRmY5gr8g7bJNKh5Bi1r9Cgp86MAh4iLC9RYYCcRFymQ3ZBaAIsbtz4u0cja5aTrNhLSc4qwf3ncdmfSSNSStjiXBjSH6brGHgpdzjCX5JB2iG2nbDkp1zltdA6yjIv8HnfY/h9GFcYcZ5tqMJSGD/zCyAI8TMHehqTn4LnkpX4N24VqEde1sFcKagQgS2d/hYzHntkQik1A7jOF4DHvqvDH7FdC5IhkOtG36geO+8jVDQYzs0ig7GJIJuHj2xV2bncE/OQ== rodolfomincholachavez@ingenieros.com"
              sshKeySecureFile: ${terraform_rsa}
              displayName: installgithubssh
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Coeperuterraformservicetestconnection'
              backendAzureRmResourceGroupName: 'rg-latam-modernization-peru-westus-001'
              backendAzureRmStorageAccountName: 'terraformperubackend'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'pipeline.terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
  - stage: tfdeploy
    condition: succeeded('tfinit')
    dependsOn: tfinit
    jobs:
      - job: apply
        steps:
          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
            displayName: tfinstall
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'Coeperuterraformservicetestconnection'
              backendAzureRmResourceGroupName: 'rg-latam-modernization-peru-westus-001'
              backendAzureRmStorageAccountName: 'terraformperubackend'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: 'pipeline.terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'Coeperuterraformservicetestconnection'
          - task: TerraformTaskV4@4
            displayName: apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'Coeperuterraformservicetestconnection'
        



